Invalid request. Data: <urllib3.response.HTTPResponse object at 0x7f3ca4bd6610>
Traceback (most recent call last):
  File "/home/zhaba/.local/lib/python3.7/site-packages/instaclient/classes/baseprofile.py", line 46, in from_username
    data = result.json()
  File "/home/zhaba/.local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 57, in <module>
    main()
  File "main.py", line 50, in main
    connect(config.LOGIN,config.PASSWORD)
  File "main.py", line 33, in connect
    print(BaseProfile.from_username("MyUsername"))
  File "/home/zhaba/.local/lib/python3.7/site-packages/instaclient/classes/baseprofile.py", line 60, in from_username
    raise InvalidInstaRequestError(request)
instaclient.errors.common.InvalidInstaRequestError: https://www.instagram.com/MyUsername/?__a=1 -> Instagram request failed.

